title: Semantic Segmentation with Polygons
type: community
group: Computer Vision
order: 1
image: /static/templates/semantic-segmentation-with-polygons.png
details: <h1>Draw a polygon around object</h1>
config: '
<View>

  <Header value="Select label and click the image to start"/>
  <Image name="image" value="$image" zoom="true"/>

  <PolygonLabels name="label" toName="image"
                 strokeWidth="3" pointSize="small"
                 opacity="0.9">
    <Label value="Airplane" background="red"/>
    <Label value="Car" background="blue"/>
  </PolygonLabels>

</View>


<!-- {
    "completions": [{
     "result": [{
        "value": {
            "points": [
                [
                    5.894842505744489,
                    42.313066522352116
                ],
                [
                    7.187278527693038,
                    42.250886807220745
                ],
                [
                    8.813240878409315,
                    39.70151689287035
                ],
                [
                    10.81442833395091,
                    36.77906849797406
                ],
                [
                    14.23312357050114,
                    37.27650652263726
                ],
                [
                    21.612502312810765,
                    37.71176479421756
                ],
                [
                    20.489348898199232,
                    43.139294698737885
                ],
                [
                    14.894545193803596,
                    56.786904350165045
                ],
                [
                    16.542616845047796,
                    56.51379118878131
                ],
                [
                    28.458038267184605,
                    37.68726338834228
                ],
                [
                    35.136089734876144,
                    37.68899856220652
                ],
                [
                    37.49543740490238,
                    36.215642404318544
                ],
                [
                    38.085274322408935,
                    35.3359427730659
                ],
                [
                    36.80729433447807,
                    34.60285974702204
                ],
                [
                    34.841171276122864,
                    34.01639332618694
                ],
                [
                    30.908925159412465,
                    33.723160115769396
                ],
                [
                    28.74618979522175,
                    33.28331030014308
                ],
                [
                    27.664822113126384,
                    32.99007708972553
                ],
                [
                    27.60101338399896,
                    32.022807298340936
                ],
                [
                    26.71654201539418,
                    30.04816123678414
                ],
                [
                    17.573259749878332,
                    14.286479191894083
                ],
                [
                    15.741422896408809,
                    13.701039087295447
                ],
                [
                    16.919032302210653,
                    17.994266521018755
                ],
                [
                    19.012560134747268,
                    23.06808076087356
                ],
                [
                    20.975242477750342,
                    27.55645489612974
                ],
                [
                    21.760315414951574,
                    33.41085594211606
                ],
                [
                    11.030980989401398,
                    33.215709223567735
                ],
                [
                    7.759850605142978,
                    27.361308262658625
                ],
                [
                    6.189702160460499,
                    27.751601597662614
                ],
                [
                    6.7130841185946535,
                    30.678802120655778
                ],
                [
                    6.9747750976617295,
                    33.606002643648935
                ],
                [
                    7.105620587195268,
                    35.167176255911954
                ],
                [
                    6.7130841185946535,
                    37.70408337583937
                ]
            ],
            "polygonlabels": [
                "Airplane"
            ]
        },
        "original_width": 600,
        "original_height": 403,
        "image_rotation": 0,
        "id": "Auwfj-r_YH",
        "from_name": "label",
        "to_name": "image",
        "type": "polygonlabels"
    },
    {
        "value": {
            "points": [
                [
                    56.720470942694114,
                    45.830111982578565
                ],
                [
                    51.730044935901,
                    54.11582621846824
                ],
                [
                    42.90087027179353,
                    54.68725478989682
                ],
                [
                    31.192616912868377,
                    53.544397647039666
                ],
                [
                    29.465169695977785,
                    54.68725478989682
                ],
                [
                    32.53618697044994,
                    57.25868336132538
                ],
                [
                    41.55731550472916,
                    60.401540578919445
                ],
                [
                    45.9718875462657,
                    64.11582621846824
                ],
                [
                    40.40566873628488,
                    76.11582621846826
                ],
                [
                    32.34423310027822,
                    75.54439772177659
                ],
                [
                    31.192616912868377,
                    77.83011193275397
                ],
                [
                    39.062113969220526,
                    80.40154062874407
                ],
                [
                    40.59760731593939,
                    86.11582621846824
                ],
                [
                    42.13311595317547,
                    89.54439764703967
                ],
                [
                    43.47668601075706,
                    88.40154050418255
                ],
                [
                    42.325027774424875,
                    77.54439826984733
                ],
                [
                    48.85096624108334,
                    66.40154065365637
                ],
                [
                    57.680293810363004,
                    89.5443958533536
                ],
                [
                    58.63983380346336,
                    86.40154050418255
                ],
                [
                    57.488202325536314,
                    78.68725478989683
                ],
                [
                    54.55745394651657,
                    61.44931624945532
                ],
                [
                    53.64940779667028,
                    57.25868390939614
                ],
                [
                    58.255956644154345,
                    48.11582621846826
                ],
                [
                    58.315984253409475,
                    46.67090454420242
                ],
                [
                    57.92267431585398,
                    45.264547397858315
                ]
            ],
            "polygonlabels": [
                "Airplane"
            ]
        },
        "original_width": 600,
        "original_height": 403,
        "image_rotation": 0,
        "id": "yCiLqxEIIM",
        "from_name": "label",
        "to_name": "image",
        "type": "polygonlabels"
    },
    {
        "value": {
            "points": [
                [
                    69.21309049900628,
                    22.549634949202005
                ],
                [
                    74.50139426376644,
                    34.83534923491629
                ],
                [
                    73.34976278583937,
                    41.40677780634486
                ],
                [
                    71.43037698929426,
                    53.97820637777344
                ],
                [
                    70.2787455113672,
                    61.40677780634488
                ],
                [
                    71.23843840963976,
                    63.40677780634486
                ],
                [
                    72.96588562653037,
                    56.54963494920201
                ],
                [
                    75.07721000272997,
                    48.26392066348772
                ],
                [
                    78.34016585685664,
                    42.835349234916286
                ],
                [
                    85.05801614476451,
                    55.978206377773446
                ],
                [
                    86.03452194784215,
                    58.812344451747485
                ],
                [
                    84.29026182614648,
                    62.549634949202
                ],
                [
                    84.6741389854555,
                    65.12106352063059
                ],
                [
                    86.59352478200061,
                    63.121063520630585
                ],
                [
                    87.55321768027314,
                    60.549634949201995
                ],
                [
                    89.85648063612727,
                    59.12106352063058
                ],
                [
                    91.96780501232689,
                    57.40677780634486
                ],
                [
                    92.73555933094492,
                    56.263920663487724
                ],
                [
                    92.54362075129043,
                    54.54963494920201
                ],
                [
                    88.51291057854571,
                    55.12106352063058
                ],
                [
                    86.2096476226916,
                    53.12106352063058
                ],
                [
                    83.3305689278739,
                    44.835349234916286
                ],
                [
                    80.83536739236527,
                    40.8353492349163
                ],
                [
                    83.71444608718295,
                    38.549634949202016
                ],
                [
                    88.3209719988912,
                    37.97820637777344
                ],
                [
                    90.43229637509081,
                    37.69249209205915
                ],
                [
                    94.84688370714454,
                    36.54963494920201
                ],
                [
                    96.57433092403515,
                    36.263920663487724
                ],
                [
                    94.27106796818104,
                    34.83534923491629
                ],
                [
                    86.59352478200061,
                    33.69249209205915
                ],
                [
                    78.91598159582018,
                    32.549634949202
                ],
                [
                    76.51360125330866,
                    31.395204861932253
                ],
                [
                    73.66190146821484,
                    25.7465346407756
                ],
                [
                    72.19813130791232,
                    23.406777806344863
                ],
                [
                    71.35374021055844,
                    21.96910288582881
                ],
                [
                    70.1983904540263,
                    20.342821957848578
                ],
                [
                    69.72005497452717,
                    20.07990007007592
                ],
                [
                    69.15086766634028,
                    20.15051147561033
                ],
                [
                    69.0048612176745,
                    21.108629454136047
                ]
            ],
            "polygonlabels": [
                "Car"
            ]
        },
        "original_width": 600,
        "original_height": 403,
        "image_rotation": 0,
        "id": "9YDn8GC9hQ",
        "from_name": "label",
        "to_name": "image",
        "type": "polygonlabels"
    },
    {
        "value": {
            "points": [
                [
                    77.77778279530708,
                    87.14285726741868
                ],
                [
                    78.73888572892093,
                    88.79186825402691
                ],
                [
                    81.04776171813313,
                    86.01068354872137
                ],
                [
                    80.41234719531053,
                    84.57163084396561
                ]
            ],
            "polygonlabels": [
                "Car"
            ]
        },
        "original_width": 600,
        "original_height": 403,
        "image_rotation": 0,
        "id": "Q8RsluXeJa",
        "from_name": "label",
        "to_name": "image",
        "type": "polygonlabels"
    },
    {
        "value": {
            "points": [
                [
                    86.68093630589533,
                    83.38961058551227
                ],
                [
                    85.3514766871728,
                    88.12628528421794
                ],
                [
                    86.38550083506809,
                    88.78721663752572
                ],
                [
                    87.64110158608382,
                    84.16069716437133
                ]
            ],
            "polygonlabels": [
                "Car"
            ]
        },
        "original_width": 600,
        "original_height": 403,
        "image_rotation": 0,
        "id": "61HfYRjz3A",
        "from_name": "label",
        "to_name": "image",
        "type": "polygonlabels"
    },
    {
        "value": {
            "points": [
                [
                    58.55721489138962,
                    93.49879161406929
                ],
                [
                    60.349945320312294,
                    87.34299605886223
                ],
                [
                    61.47561845086712,
                    87.9026137444404
                ],
                [
                    59.72457424045554,
                    94.30712840414698
                ]
            ],
            "polygonlabels": [
                "Car"
            ]
        },
        "original_width": 600,
        "original_height": 403,
        "image_rotation": 0,
        "id": "zEAj-Yvpyp",
        "from_name": "label",
        "to_name": "image",
        "type": "polygonlabels"
    }]


}]}

-->
'
