name: Algolia Indexer

on:
  push:
    branches: [ 'develop' ]
    paths:
      - 'docs/**'
      - '.github/workflows/algolia-crawler.yml'

jobs:
  algolia_indexer:
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: "M7RXTHKYPM"
      API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      INDEX_NAME: "ghaction"
      CONFIG: >
        {"index_name": "ghaction",
        "stop_urls": ["https://docs.humansignal.com/guide/index.html", "https://docs.humansignal.com/guide/notion-faq.html", "https://labelstud.io/sdk/index.html"], 
        "selectors_exclude": [".home-page-index"], 
        "start_urls": ["https://docs.humansignal.com/guide", "https://docs.humansignal.com/templates", "https://docs.humansignal.com/tags", "https://labelstud.io/sdk/"],
        "selectors": {
        "lvl0": ".content h1, .ResourcesBannerHeading",
        "lvl1": ".content h2, .ResourcesContent h2",
        "lvl2": ".content h3, .ResourcesContent h3",
        "lvl3": ".content h4, .ResourcesContent h4",
        "lvl4": ".content h5, .ResourcesContent h5",
        "lvl5": ".content h6, .ResourcesContent h6", 
        "content": ".content-markdown > *"
        }}
    name: Index Algolia
    steps:
      - name: Algolia Docsearch Action
        id: algolia
        uses:  adapttive/algolia-docsearch-action@1.1.1
