name: 'Follow Merge: LSF Sync'

on:
  schedule:
    - cron: '0 4 * * 1'
  workflow_call:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Create dispatch event
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const { repo, owner } = context.repo;
            
            const lsf_owner = owner;
            const lsf_repo = 'label-studio-frontend';
            
            const {data: lsf_repo_data} = await github.rest.repos.get({
              owner: lsf_owner,
              repo: lsf_repo,
            });
            
            const {data: lsf_commit} = await github.rest.repos.getCommit({
              owner: lsf_owner,
              repo: lsf_repo,
              ref: lsf_repo_data.default_branch
            });
            
            const result = await github.rest.repos.createDispatchEvent({
              owner,
              repo,
              event_type: 'upstream_repo_update',
              client_payload: {
                branch_name: 'fb-scheduled-lsf-sync',
                base_branch_name: lsf_repo_data.default_branch,
                repo_name: lsf_repo_data.full_name,
                commit_sha: lsf_commit.sha,
                title: "feat: Scheduled LSF sync",
                html_url: lsf_commit.html_url,
                actor: lsf_commit.commit.author.name,
                author_username: lsf_commit.commit.author.name,
                author_email: lsf_commit.commit.author.email,
                event_action: 'merged'
              }
            });
            return result
