name: Check for broken links

on:
  pull_request:
    branches: ["develop"]
    paths:
      - "docs/**"
      - ".github/workflows/link-check.yml"
  workflow_dispatch:

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install broken-link-checker

      - name: Run broken-link-checker and fail on broken links for Label Studio Docs
        run: |
          npx blc https://deploy-preview-${{ github.event.pull_request.number }}--label-studio-docs-new-theme.netlify.app -roef --exclude "/api"
          if [ $? -eq 0 ]; then
            exit 1
          fi

      - name: Run broken-link-checker and fail on broken links for Human Signal Docs
        run: |
          npx blc https://deploy-preview-${{ github.event.pull_request.number }}--heartex-docs.netlify.app -roef --exclude "/api"
          if [ $? -eq 0 ]; then
            exit 1
          fi
