# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: "Close stale issues and PRs"

on:
  schedule:
    - cron: "30 1 * * *" # At 01:30

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1 # never closed automatically
          stale-pr-message: "This PR is stale because it has been open 172 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          close-pr-message: "This PR was closed because it has been stalled for 10 days with no activity."
          days-before-pr-stale: 172
          days-before-pr-close: 10
          stale-pr-label: "no-pr-activity"
          exempt-pr-labels: "awaiting-approval,work-in-progress"
          exempt-draft-pr: true
